name: openproject_dart_sdk
version: 1.0.0
description: Dart SDK for the OpenProject Software
authors:
  - Simon Bullik <sbu@wbt-solutions.de>
homepage: https://code.wbt-solutions.de/sbu/openproject_dart_sdk
issue_tracker: https://code.wbt-solutions.de/sbu/openproject_dart_sdk/issues
repository: https://code.wbt-solutions.de/sbu/openproject_dart_sdk.git
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: '>=0.12.0 <0.13.0'
dev_dependencies:
  test: ^1.3.0
