name: OpenAPI spec validation
on:
  - push
  - pull_request
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: swagger-validator
        uses: mbowman100/swagger-validator-action@master
        with:
          files: openProject_swagger.yaml
